/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Student;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ZVOOOOOOOOOOOOO
 */
public class StudentControlBoard extends javax.swing.JFrame {

    /**
     * Creates new form StudentControlBoard
     */
    Connection con;
    PreparedStatement pst;
    
    public StudentControlBoard() {
        initComponents();
    }
    
    public void my_update(String Name,String Password) {
        Name_lb.setText(Name);
        Password_lb.setText(Password);
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/studentdb", "root", "");
            pst = con.prepareStatement("SELECT * FROM record WHERE Name=? AND Password=?");
            pst.setString(1, Name);
            pst.setString(2, Password);
            ResultSet rs = pst.executeQuery();
            
            if(rs.next())
            {
                ID_lb.setText(rs.getString("ID"));
                Mobile_lb.setText(rs.getString("Mobile"));
                Course_lb.setText(rs.getString("Course"));
            }
            else
            {   
                JOptionPane.showMessageDialog(null, "Error");
            }
            
            
            
            con.close();
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }
    
    
            
            
        

    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        back_btn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Name_lb = new javax.swing.JLabel();
        Mobile_lb = new javax.swing.JLabel();
        Course_lb = new javax.swing.JLabel();
        Password_lb = new javax.swing.JLabel();
        ID_lb = new javax.swing.JLabel();
        XO_btn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student System ");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("My data :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 105, -1));

        back_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Student/back-btn.png"))); // NOI18N
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });
        getContentPane().add(back_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 120, 50));

        jLabel2.setText("Name :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 80, 30));

        jLabel3.setText("Mobile :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 80, 30));

        jLabel4.setText("Course : ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 80, 30));

        jLabel5.setText("My Password:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 80, 30));

        jLabel7.setText("ID :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 80, 30));

        Name_lb.setText("....");
        getContentPane().add(Name_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 80, 30));

        Mobile_lb.setText("....");
        getContentPane().add(Mobile_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 80, 30));

        Course_lb.setText("....");
        getContentPane().add(Course_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 80, 30));

        Password_lb.setText("....");
        getContentPane().add(Password_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 80, 30));

        ID_lb.setText("....");
        getContentPane().add(ID_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 80, 30));

        XO_btn.setText("Cheat and Play");
        XO_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XO_btnActionPerformed(evt);
            }
        });
        getContentPane().add(XO_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 210, 40));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, 170, 310));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 374, 570, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        dispose();
        new FirstFrame().setVisible(true);
    }//GEN-LAST:event_back_btnActionPerformed

    private void XO_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XO_btnActionPerformed
        new TicTacToe().setVisible(true);
    }//GEN-LAST:event_XO_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentControlBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentControlBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentControlBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentControlBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentControlBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Course_lb;
    private javax.swing.JLabel ID_lb;
    private javax.swing.JLabel Mobile_lb;
    private javax.swing.JLabel Name_lb;
    private javax.swing.JLabel Password_lb;
    private javax.swing.JButton XO_btn;
    private javax.swing.JButton back_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    
}
